### PR TITLE
Implement Wi-Fi, File server ON/OFF Switch

### PR DESCRIPTION
**Pull request by KD-MM2**
I added Wi-Fi Switch and File server Switch under Options(VOLUME button) menu.

### CODE REVIEW

**Comment by KD-MM2** [comment]
Checkout these images:

**Comment by ducalex** [comment]
I was working on something similar but I guess we can merge your version for now. It seems to work well :) .

Can you just get rid of `base.sdkconfig` from your PR? It will break compatibility with esp-idf 4.0/4.1 and it doesn't seem related to your wifi changes anyway.

**Comment by ducalex** [comment]
Oh, and maybe wifi_state and webui_state should default to true?

I'm not too sure myself, what do you think?

**Comment by Cralex** [comment]
I would think WiFi and the web ui should be on by default. With the Mini Game Box port that I’m working on, the only way to access the SD card is to open the case. The stock firmware has WiFi file transfer, so you could successfully install and use Retro-Go by uploading the firmware and your WiFi credentials using the stock firmware without opening the unit. (Of course, a future update that adds back WiFi host mode would prevent anyone from ever getting locked out of the webui.)

**Comment by KD-MM2** [comment]
> I was working on something similar but I guess we can merge your version for now. It seems to work well :) .
> 
> Can you just get rid of `base.sdkconfig` from your PR? It will break compatibility with esp-idf 4.0/4.1 and it doesn't seem related to your wifi changes anyway.

> Oh, and maybe wifi_state and webui_state should default to true?
> 
> I'm not too sure myself, what do you think?

OK all done. Now I'm developing Wi-Fi scan. We will have a dialog show up when press SELECT on WiFi switch, this dialog show a list of scanned ssid, select one and it will be saved into wifi.json.

**Comment by ducalex** [comment]
Thanks!

**Comment by ducalex** [comment]
I've moved the wifi options to a sub menu because you said you wanted to add more options, and I also have some to add. That would make the normal options menu too long.

It's a minimal change but be sure to pull before continuing your work!

**Pull request merged**
