### PR TITLE
add new hardware port

### PR DESCRIPTION
**Pull request by FantasyGmm**

### CODE REVIEW

**Comment by ducalex** [comment]
That new PR looks pretty good. If I understood correctly we are waiting for you to test it first?

**Comment by FantasyGmm** [comment]
Maybe you can merge first, and then I test and fix it, so that you can continue to submit the code, and it will not conflict with this PR

**Comment by ducalex** [comment]
Is there any reason why the `#ifndef SPI_DMA_CH_AUTO` doesn't work for you?

Because your change to `#if CONFIG_IDF_TARGET_ESP32` causes two issues:
- It redefines the constant when building for esp32 on esp-idf 4.3+
- It causes build to fail when target is esp32-s2 on esp-idf 4.1 or 4.2

**Comment by FantasyGmm** [comment]
If there is no Define Target, then he will also fail on ESP32S3

**Comment by FantasyGmm** [comment]
Without this define, then it will also fail on ESP32S3, S3 can only use IDF's auto macro

**Comment by FantasyGmm** [comment]
If esp32s2 also crashes, maybe it should be modified again

**Comment by ducalex** [comment]
Okay we're both dumb, neither version will work correctly across all versions/targets. My version won't work with >= 4.4 because SPI_DMA_CH_AUTO isn't a macro it's an enum. Yours won't work with >=4.4+ESP32 for the same reason and !ESP32.

For now I pushed 1892c16342f786cad57f248b187ddf076abb51b2 which uses the esp-idf version rather than the ndef or target. 
You can just remove the two SPI_DMA_CH_AUTO blocks completely and I think it'll be ready to merge

**Comment by FantasyGmm** [comment]
Okay, I deleted the define for DMA

**Comment by ducalex** [comment]
I've modified storage to always use the gpio matrix when available, not just esplay-s3 target:

https://github.com/ducalex/retro-go/commit/1912b3b4384343df10ea43dae3aa5bfb4e8f2ec4#diff-cc6c0f0d2a4c8128878551cd68e5558888a775d79ce1d630d83ae8a45abd6bf6R95-R105

Let me know if this breaks things or if you think this is a regression!

**Comment by FantasyGmm** [comment]
I allocated pins according to PCB layout, so I must specify this pins. IO MUX of S3 is very powerful, so you can assign peripherals to almost any pin

**Comment by ducalex** [comment]
My changes still allow you to specify your pins:

````c
#if SOC_SDMMC_USE_GPIO_MATRIX
    slot_config.clk = RG_GPIO_SDSPI_CLK;
    slot_config.cmd = RG_GPIO_SDSPI_CMD;
    slot_config.d0 = RG_GPIO_SDSPI_D0;
    // d1 and d3 normally not used in width=1 but sdmmc_host_init_slot saves them, so just in case
    slot_config.d1 = slot_config.d3 = -1;
#endif
````

**Comment by FantasyGmm** [comment]
Ok, I may need to fix it, I am still waiting for my PCB, when I am free, I may port a TinyUSB to S3, so that I can copy your game through USB or FW, I will test another project, its control may be a little slow, but the file transfer speed is quite fast

**Comment by FantasyGmm** [comment]
Now I have the newly designed board. I re-clone the warehouse and find some mistakes. I will sort out and submit the new code later

**Pull request merged**
