### PR TITLE
Adding support for mutliple languages

### PR DESCRIPTION
**Pull request by raphatex**
- Adding support for mutliple languages

### CODE REVIEW

**Comment by raphatex** [comment]
I will try to add a way to specify the language directly in the build command (rg_tool.py)

**Comment by ducalex** [comment]
Can you make make a second PR for your new target instead of combining language+target?

The new target can probably be merged quickly but the localization is a bigger change and will need some time to discuss.

**Comment by raphatex** [comment]
Sure no problem !

**Comment by ducalex** [comment]
Thanks. So for the multiple language support I think it's a good idea but I don't like making it a compile-time option. (A target could specify a default language of course but the build should always contain all languages.)

I'm not really sure what is the *best* way to achieve this. 

As far as I know the *common* way in C is to use gettext, which is convenient because the code would still contain the english text, just wrapped in `_(...)`. So it's a pretty minimal change to our code base. Of course we wouldn't use the full gettext, we'd just implement the lookup `_()` function ourselves and none of the rest.

A simpler way that is reasonably common in embedded is a struct or enum+array. It's most similar to your current code, except we can have multiple languages at once and point to the active one.

````
typedef struct
{
    const char *App_unresponsive;  // "App unresponsive... Hold MENU to quit!"
    const char *Reset_all_settings ;  // "Reset all settings"
    const char *Reboot_to_factory;  // "Reboot to factory "
    const char *Reboot_to_launcher;  // "Reboot to launcher"
} translation_t;

translation_t lang_en = {
    .App_unresponsive = "App unresponsive... Hold MENU to quit!",
    .Reset_all_settings = "Reset all settings",
    .Reboot_to_factory = "Reboot to factory ",
    .Reboot_to_launcher = "Reboot to launcher",
};

translation_t lang_fr = {
...
};

translation_t *lang_active= &lang_en;
````


Or the enum way instead:
````
enum
{
    TEXT_App_unresponsive,  // "App unresponsive... Hold MENU to quit!"
    TEXT_Reset_all_settings ,  // "Reset all settings"
    TEXT_Reboot_to_factory,  // "Reboot to factory "
    TEXT_Reboot_to_launcher,  // "Reboot to launcher"

    TEXT_COUNT,
};

const char *lang_en[TEXT_COUNT] = {
    "App unresponsive... Hold MENU to quit!",
    "Reset all settings",
    "Reboot to factory ",
    "Reboot to launcher",
};

const char *lang_fr[TEXT_COUNT] = {
...
}

const char **lang_active= &lang_en;
````

**Comment by ducalex** [comment]
I think the gettext method is the nicest because the source (english) text remains in the code rather than a more cryptic key. But the others are simpler to implement and do not require an hashmap, so I don't know...

Let me know what is your opinion, or if you have more ideas on how to achieve the goal of all languages being in the build!

**Comment by ducalex** [comment]
Also, in my opinion, log entries (RG_LOGx) and debug messages shouldn't be translated. Logs are for the developer and the entire code is in english, so it's safe to assume that the person reading the serial log can understand it.

**Comment by raphatex** [comment]
Yeah ! I do agree that we shouldn't translate logs !
Personnally I'm not as talented as you so I don't know if I could manage to implement the lookup _() function for gettext.
Struct seems pretty easy on the other hand as you said so I could manage it but I agree in the fact that the source text will be "hidden away". 
So I guess I will try atleast to implement gettext method first and if I do not manage to I will use the "struct" way

**Pull request closed without merging**
