### PR TITLE
Added Retro ESP32

### PR DESCRIPTION
**Pull request by 32teeth**
* Allows for `-target retro-esp32`
* Menu button combo like GBC
* Margin right since MGB screen protector covers 20 pixels of right hand side

### CODE REVIEW

**Comment by ducalex** [comment]
Can you remove the .DS_Store files as well as the changes you made to rg_system.c?

**Comment by 32teeth** [comment]
Done

**Comment by ducalex** [comment]
Thanks!

**Comment by ducalex** [comment]
Looking at it more closely I couldn't see any reason not to fully reuse the ODROID-GO input code. 

I've changed it in 8def604d536. The behaviour should be identical but please let me know if I missed something!

**Pull request merged**
