### PR TITLE
feat: new theme creator html

### PR DESCRIPTION
**Pull request by 32teeth**
# New Theme Creator HTML
> Better interactivity

* Removed jQuery dependency
* Added custom HTML Element for palette chip
* Better responsive

Screenshot 2023-04-20 at 10 03 07 PM

### CODE REVIEW

**Comment by 32teeth** [comment]
Sorry about the multiple commits, something wonky happened when i attempted to rebase and squash

**Comment by ducalex** [comment]
Wow that looks good! 

Though I think I broke most theming support at some point, right? I see some support for dialog theming in rg_gui.c (line ~81-86) but the launcher doesn't have color theming, just images?

We should document and/or fix what a theme is so that the editor creates something valid.

**Comment by 32teeth** [comment]
@ducalex 

I only reused all the props you created in the original theme page.
You can play with a working copy here https://codepen.io/32teeth/pen/BaqQEXP

If you remove
```
  {
    title: 'Dialog > Background',
    property: "dialog_bg",
    color: "#000000"
  },
  {
    title: 'Dialog > Foreground',
    property: "dialog_fg",
    color: "#FFFFFF"
  }
```

It just won't show it

**Comment by ducalex** [comment]
Alright I've finally come around and finished the theme documentation and it seems to work. Can you make your editor follow the format described in https://github.com/ducalex/retro-go/blob/dev/THEMING.md ?

Also I'm not sure if it's easy/possible but it would be nice if the editor limited the colours to RGB565, because retro-go will convert RGB888 to 565 by discarding the extra bits, so the colour on screen could end up pretty different.

**Pull request closed without merging**
