### PR TITLE
Retro ESP32 screen offset

### PR DESCRIPTION
**Pull request by 32teeth**
Since Retro ESP32 only has Select Start, added select + A to jump to options directly

### CODE REVIEW

**Comment by ducalex** [comment]
The title of your PR doesn't seem to match the description. Also the there are conflicts so I can't merge it anyway.

Right now START+SELECT should open the options on retro-esp32 but I'm fine with changing it to select+a if it's better, just make sure your PR is mergeable :).

**Comment by ducalex** [comment]
I think you should start over with this PR, it should really only include rg_input.c. I think we got out of sync a bit...

**Comment by 32teeth** [comment]
> I think you should start over with this PR, it should really only include rg_input.c. I think we got out of sync a bit...

If you check the [Files Changed](https://github.com/ducalex/retro-go/pull/20/files) tabs it only has one file.
I did a rebase before the commit

**Comment by ducalex** [comment]
But your code is still incompatible with https://github.com/ducalex/retro-go/commit/8def604d5360fe4a6149f03ee926add5022cf021 because I removed driver 32.

You should move your change to the `RG_GAMEPAD_DRIVER == 1` block instead, something like:

````
    #ifdef RG_TARGET_RETRO_ESP32
    if (state == (RG_KEY_SELECT|RG_KEY_A))
        state = RG_KEY_OPTION;
    if (state == (RG_KEY_START|RG_KEY_SELECT))
        state = RG_KEY_MENU;
    #endif
````

Then it would work and I can merge it. But can you also fix the title of the PR please?

**Pull request closed without merging**
