### PR TITLE
fix s3 error

### PR DESCRIPTION
**Pull request by FantasyGmm**

### CODE REVIEW

**Comment by FantasyGmm** [comment]
doom still crash, i will fix it,may be next week

**Comment by ducalex** [comment]
While you're working on this, can you check if you could use gamepad driver #3 and remove #5? They're basically identical and #3 has constants that should allow you to configure it in your target file (check mrgc-g32.h).

If you don't think it's a good idea then it's fine too. But I like reusing code where possible :) .

**Comment by FantasyGmm** [comment]
I tried it, but the current I2C reading will fail. Maybe when I fix the DOOM later, I will try to fix this problem, and some of my keys are directly connected to the GPIO. The GPIO is not initialized in the init, which may cause the key to fail to read the button correctly.

**Comment by ducalex** [comment]
Sure but we could just add the block. I did it in https://github.com/ducalex/retro-go/blob/fc5d8bf92bc1e8921847d0a44fb71599ab429211/components/retro-go/rg_input.c

But yeah that's your call, we won't do it.

Is your PR here ready to review? You didn't put any description so I'm not sure if it's a work on progress or if you want me to merge ASAP?

**Comment by FantasyGmm** [comment]
I re-tested the code in my warehouse, but I still can't read I2C. I will find a time to fix this problem in a few days and migrate it to the existing code

**Comment by ducalex** [comment]
Don't waste your time if it doesn't work, it's only a few lines duplicated.

Just let me know when this PR is ready to be merged :) .

**Comment by Wind-stormger** [comment]
I'd like to make some PR suggestions.

Work based on the latest commit of the main branch of ducalex/retro-go to minimize conflicts.

After forking the main branch of ducalex/retro-go, keep the main branch unchanged, create your dev branch based on the main branch, and keep the minimum code changes under the premise of achieving the purpose.

For example a change to targets/esplay-s3.h, maybe it is not necessary to replace all GPIO_NUM.

Indicate the reason for the change of each file one by one in the commit, or add multiple commits.

If the multi-line information of the commit bothers you, it should be no problem to explain it directly in the conversation of the PR.

If you have any other doubts, please let me know and we can discuss it.

**Comment by FantasyGmm** [comment]
Yes, I plan to restart this project in the near future. I didn't have time to repair it because of my studies

**Comment by FantasyGmm** [comment]
I recently restarted this project, but based on the fw file compiled with the latest code, the odroid-go-multi-firmware cannot be flashed to display invalid firmware.

**Comment by ducalex** [comment]
This is not really relevant anymore and the build system has diverged too much for this PR.

Still happy to merge fixes for your target if needed, just make a new PR!

**Comment by FantasyGmm** [comment]
> This is not really relevant anymore and the build system has diverged too much for this PR.
> 
> Still happy to merge fixes for your target if needed, just make a new PR!

I forgot about this pr, I'll take the time to make a new version of the hardware, the previous one has been having some reset issues, sometimes it doesn't boot up properly

**Pull request closed without merging**
