### PR TITLE
Adding Retro ESP32 option to support ILI9342 2.6 inch screen

### PR DESCRIPTION
**Pull request by 32teeth**
# Adding Support for [Retro ESP32](https://www.tindie.com/products/handheld-gaming/retro-esp32/)

> What changed / added

* Added new target `retro-esp32`
* Added `RG_TARGET_RETRO_ESP32` to display
* Added retro-esp32 target header file *for eventual support of new hardware*

> Testing on ESP-IDF 4.1

Full Clean Everything
```
cd handy-go && idf.py fullclean && cd ../ && cd nofrendo-go && idf.py fullclean && cd ../ && cd snes9x-go && idf.py fullclean && cd ../ && cd pce-go && idf.py fullclean && cd ../ && cd gnuboy-go && idf.py fullclean && cd ../ && cd launcher && idf.py fullclean && cd ../ && cd prboom-go && idf.py fullclean && cd ../ && cd smsplusgx-go && idf.py fullclean && cd ../
```

Set Target & Build Launcher
```
python rg_tool.py --target retro-esp32 build launcher

# Build Snip Confirmation
# Target: RG_TARGET_RETRO_ESP32
```

Flash Launcher
*Note:* `$PORT` and `$BAUD` are in my `~/.zshrc` file based on what i plug in
```
python rg_tool.py  --port $PORT --baud $BAUD flash launcher
```

### CODE REVIEW

**Comment by 32teeth** [comment]
> Templates

Adding generic intake templates for both issues and features

With issues now being open for this repository, the templates allow affordances for contributors to participate in meaningful manner

**Review by ducalex — CHANGES_REQUESTED** [review]
This doesn't seem right, can you replace with a list of esp32 devices that we support instead? 

Maybe something like:
- ODROID-GO
- MRGC-G32
- RetroESP32
- Other

**Comment by 32teeth** [comment]
Can you explain further?

The addition of retro-ESP32 followed pattern for setting base environment variables and tests provided

Would love to understand what's not working to fix it

**Comment by 32teeth** [comment]
> Please check changed files for 

* Added new target retro-esp32
* Added RG_TARGET_RETRO_ESP32 to display
* Added retro-esp32 target header file for eventual support of new hardware

This was done by adding new config file as well as `or ||` statement in display files

> Test script all pass
Successful build onto RetroESP32 device?

```
python rg_tool.py --target retro-esp32 build launcher
```

In your PR review, please provide additional code feedback

**Comment by ducalex** [comment]
The part about adding support for retro-esp32 is perfectly well done and I would have accepted that part instantly!

But you also included github templates in the PR and I think [this section](https://github.com/ducalex/retro-go/pull/6/files#diff-185833cb26d7ac66a4d39042fd576a820c2c2c6d05ad18973bb9c7dce77267c5R26-R35) needs to changed as I described.

**Comment by 32teeth** [comment]
Fixed the issue template
Thanks

**Comment by 32teeth** [comment]
Something went wrong with my local git. Removing this PR and will post a new one

**Pull request closed without merging**
